name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  hugo:
    name: Hugo
    runs-on: ubuntu-latest
    steps:
    - name: Compile content on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd /home/pengjl/PengjlsBlog
          git fetch --all
          git reset --hard origin/main
          git pull
          hugo --destination=./public
